-- ============================================================
-- SCRIPT SQL: INSERÇÃO DAS PALAVRAS E FRASES DO ESTÁGIO T2
-- Tabela: public.palavras_spelling
-- Nível: T2 (135 itens únicos deduplicados)
-- Execute este script no SQL Editor do Supabase
-- ============================================================

-- Remover registros anteriores de nível T2 (opcional, para recarga limpa)
DELETE FROM public.palavras_spelling WHERE level = 'T2';

INSERT INTO public.palavras_spelling (level, word, sentence, audio_url) VALUES
('T2', 'meals', 'Healthy meals are essential for good growth.', 'https://api.dictionaryapi.dev/media/pronunciations/en/meals-us.mp3'),
('T2', 'sugar', 'Do not put too much sugar in your tea.', 'https://api.dictionaryapi.dev/media/pronunciations/en/sugar-us.mp3'),
('T2', 'throat', 'I have a sore throat today.', 'https://api.dictionaryapi.dev/media/pronunciations/en/throat-us.mp3'),
('T2', 'useful', 'A dictionary is very useful for learning vocabulary.', 'https://api.dictionaryapi.dev/media/pronunciations/en/useful-us.mp3'),
('T2', 'creative', 'She is a very creative artist.', 'https://api.dictionaryapi.dev/media/pronunciations/en/creative-us.mp3'),
('T2', 'nervous', 'I felt nervous before speaking in public.', 'https://api.dictionaryapi.dev/media/pronunciations/en/nervous-us.mp3'),
('T2', 'healthy', 'Eating fruits keeps your body healthy.', 'https://api.dictionaryapi.dev/media/pronunciations/en/healthy-us.mp3'),
('T2', 'sweeter than', 'Apples are sweeter than lemons.', 'https://api.dictionaryapi.dev/media/pronunciations/en/sweeter-us.mp3'),
('T2', 'busier than', 'Mondays are busier than Sundays.', 'https://api.dictionaryapi.dev/media/pronunciations/en/busier-us.mp3'),
('T2', 'more dangerous', 'Lions are more dangerous than rabbits.', 'https://api.dictionaryapi.dev/media/pronunciations/en/more-us.mp3'),
('T2', 'farther', 'He ran farther than everyone else.', 'https://api.dictionaryapi.dev/media/pronunciations/en/farther-us.mp3'),
('T2', 'worse', 'Today the weather is worse than yesterday.', 'https://api.dictionaryapi.dev/media/pronunciations/en/worse-us.mp3'),
('T2', 'faster', 'Cheetahs run faster than horses.', 'https://api.dictionaryapi.dev/media/pronunciations/en/faster-us.mp3'),
('T2', 'as tasty as', 'This cake is as tasty as that one.', 'https://api.dictionaryapi.dev/media/pronunciations/en/as-us.mp3'),
('T2', 'as good as', 'Her English is as good as his.', 'https://api.dictionaryapi.dev/media/pronunciations/en/as-us.mp3'),
('T2', 'more fluently than', 'She speaks English more fluently than last year.', 'https://api.dictionaryapi.dev/media/pronunciations/en/more-us.mp3'),
('T2', 'more slowly', 'Please read the text more slowly.', 'https://api.dictionaryapi.dev/media/pronunciations/en/more-us.mp3'),
('T2', 'do badly in Science', 'I need to study so I don''t do badly in Science.', 'https://api.dictionaryapi.dev/media/pronunciations/en/do-us.mp3'),
('T2', 'do well in Portuguese', 'Students who practice read and do well in Portuguese.', 'https://api.dictionaryapi.dev/media/pronunciations/en/do-us.mp3'),
('T2', 'make friends easily', 'Friendly people make friends easily.', 'https://api.dictionaryapi.dev/media/pronunciations/en/make-us.mp3'),
('T2', 'make fun of friends', 'You should never make fun of friends.', 'https://api.dictionaryapi.dev/media/pronunciations/en/make-us.mp3'),
('T2', 'take a nap', 'I usually take a nap after lunch.', 'https://api.dictionaryapi.dev/media/pronunciations/en/take-us.mp3'),
('T2', 'take care of', 'Please take care of your little sister.', 'https://api.dictionaryapi.dev/media/pronunciations/en/take-us.mp3'),
('T2', 'take trips to', 'Our family loves to take trips to the beach.', 'https://api.dictionaryapi.dev/media/pronunciations/en/take-us.mp3'),
('T2', 'Bruce used to work.', 'Bruce used to work.', 'https://api.dictionaryapi.dev/media/pronunciations/en/bruce-us.mp3'),
('T2', 'never used to watch', 'never used to watch', 'https://api.dictionaryapi.dev/media/pronunciations/en/never-us.mp3'),
('T2', 'didn''t use to be', 'Practice saying and spelling "didn''t use to be".', 'https://api.dictionaryapi.dev/media/pronunciations/en/didnt-us.mp3'),
('T2', 'Where did you use to live?', 'Practice saying and spelling "Where did you use to live?".', 'https://api.dictionaryapi.dev/media/pronunciations/en/where-us.mp3'),
('T2', 'started writing songs', 'She started writing songs when she was ten.', 'https://api.dictionaryapi.dev/media/pronunciations/en/started-us.mp3'),
('T2', 'became famous', 'The young artist became famous overnight.', 'https://api.dictionaryapi.dev/media/pronunciations/en/became-us.mp3'),
('T2', 'felt lonely', 'He felt lonely when he moved to a new city.', 'https://api.dictionaryapi.dev/media/pronunciations/en/felt-us.mp3'),
('T2', 'was a Star Trek fan', 'My uncle was a Star Trek fan in his youth.', 'https://api.dictionaryapi.dev/media/pronunciations/en/was-us.mp3'),
('T2', 'worked at Starbucks', 'She worked at Starbucks during college.', 'https://api.dictionaryapi.dev/media/pronunciations/en/worked-us.mp3'),
('T2', 'were friends', 'They were friends for many years.', 'https://api.dictionaryapi.dev/media/pronunciations/en/were-us.mp3'),
('T2', 'about ten hours', 'The flight to London takes about ten hours.', 'https://api.dictionaryapi.dev/media/pronunciations/en/about-us.mp3'),
('T2', 'over twenty songs', 'The band performed over twenty songs.', 'https://api.dictionaryapi.dev/media/pronunciations/en/over-us.mp3'),
('T2', 'under eighteen years old', 'You must be under eighteen years old to join this category.', 'https://api.dictionaryapi.dev/media/pronunciations/en/under-us.mp3'),
('T2', 'in the universe', 'Earth is just a small planet in the universe.', 'https://api.dictionaryapi.dev/media/pronunciations/en/in-us.mp3'),
('T2', 'in the world', 'It is one of the most famous places in the world.', 'https://api.dictionaryapi.dev/media/pronunciations/en/in-us.mp3'),
('T2', 'on Earth', 'Water is essential for life on Earth.', 'https://api.dictionaryapi.dev/media/pronunciations/en/on-us.mp3'),
('T2', 'on the fifth floor', 'His apartment is on the fifth floor.', 'https://api.dictionaryapi.dev/media/pronunciations/en/on-us.mp3'),
('T2', 'in 1983', 'My parents met in 1983.', 'https://api.dictionaryapi.dev/media/pronunciations/en/in-us.mp3'),
('T2', 'in three weeks', 'The final exams will start in three weeks.', 'https://api.dictionaryapi.dev/media/pronunciations/en/in-us.mp3'),
('T2', 'on February 21st', 'Her birthday is on February 21st.', 'https://api.dictionaryapi.dev/media/pronunciations/en/on-us.mp3'),
('T2', 'on Monday morning', 'We have a team meeting on Monday morning.', 'https://api.dictionaryapi.dev/media/pronunciations/en/on-us.mp3'),
('T2', 'the largest hot dog', 'They prepared the largest hot dog at the festival.', 'https://api.dictionaryapi.dev/media/pronunciations/en/the-us.mp3'),
('T2', 'the heaviest man', 'He entered the records as the heaviest man.', 'https://api.dictionaryapi.dev/media/pronunciations/en/the-us.mp3'),
('T2', 'the least expensive restaurant', 'We ate at the least expensive restaurant in town.', 'https://api.dictionaryapi.dev/media/pronunciations/en/the-us.mp3'),
('T2', 'the furthest galaxy', 'Astronomers discovered the furthest galaxy.', 'https://api.dictionaryapi.dev/media/pronunciations/en/the-us.mp3'),
('T2', 'the worst album', 'Critics called it the worst album of the year.', 'https://api.dictionaryapi.dev/media/pronunciations/en/the-us.mp3'),
('T2', 'Go straight ahead.', 'Go straight ahead.', 'https://api.dictionaryapi.dev/media/pronunciations/en/go-us.mp3'),
('T2', 'Cross the street.', 'Cross the street.', 'https://api.dictionaryapi.dev/media/pronunciations/en/cross-us.mp3'),
('T2', 'Turn right.', 'Turn right.', 'https://api.dictionaryapi.dev/media/pronunciations/en/turn-us.mp3'),
('T2', 'Turn left.', 'Turn left.', 'https://api.dictionaryapi.dev/media/pronunciations/en/turn-us.mp3'),
('T2', 'on the corner of', 'The bakery is on the corner of Main Street.', 'https://api.dictionaryapi.dev/media/pronunciations/en/on-us.mp3'),
('T2', 'across from', 'The park is across from the library.', 'https://api.dictionaryapi.dev/media/pronunciations/en/across-us.mp3'),
('T2', 'near here', 'Is there a pharmacy near here?', 'https://api.dictionaryapi.dev/media/pronunciations/en/near-us.mp3'),
('T2', 'far from here', 'The airport is not far from here.', 'https://api.dictionaryapi.dev/media/pronunciations/en/far-us.mp3'),
('T2', 'two blocks away', 'My school is just two blocks away.', 'https://api.dictionaryapi.dev/media/pronunciations/en/two-us.mp3'),
('T2', 'around the corner', 'The supermarket is around the corner.', 'https://api.dictionaryapi.dev/media/pronunciations/en/around-us.mp3'),
('T2', 'slowly', 'The turtle walked slowly across the yard.', 'https://api.dictionaryapi.dev/media/pronunciations/en/slowly-us.mp3'),
('T2', 'really', 'I am really excited about our trip.', 'https://api.dictionaryapi.dev/media/pronunciations/en/really-us.mp3'),
('T2', 'well', 'She did very well on her English test.', 'https://api.dictionaryapi.dev/media/pronunciations/en/well-us.mp3'),
('T2', 'fast', 'Cheetahs run very fast.', 'https://api.dictionaryapi.dev/media/pronunciations/en/fast-us.mp3'),
('T2', 'hard', 'They worked hard to finish the project.', 'https://api.dictionaryapi.dev/media/pronunciations/en/hard-us.mp3'),
('T2', 'happily', 'The children played happily in the park.', 'https://api.dictionaryapi.dev/media/pronunciations/en/happily-us.mp3'),
('T2', 'carefully', 'Handle the fragile glass carefully.', 'https://api.dictionaryapi.dev/media/pronunciations/en/carefully-us.mp3'),
('T2', 'quickly', 'Please answer the message quickly.', 'https://api.dictionaryapi.dev/media/pronunciations/en/quickly-us.mp3'),
('T2', 'easily', 'He solved the puzzle easily.', 'https://api.dictionaryapi.dev/media/pronunciations/en/easily-us.mp3'),
('T2', 'lose', 'Never give up, even if you lose a game.', 'https://api.dictionaryapi.dev/media/pronunciations/en/lose-us.mp3'),
('T2', 'throw away', 'Do not throw away plastic bottles; recycle them.', 'https://api.dictionaryapi.dev/media/pronunciations/en/throw-us.mp3'),
('T2', 'everyone', 'Everyone enjoyed the school party.', 'https://api.dictionaryapi.dev/media/pronunciations/en/everyone-us.mp3'),
('T2', 'someone', 'Someone left a backpack under the chair.', 'https://api.dictionaryapi.dev/media/pronunciations/en/someone-us.mp3'),
('T2', 'no one', 'No one answered the phone when I called.', 'https://api.dictionaryapi.dev/media/pronunciations/en/no-us.mp3'),
('T2', 'anyone', 'Does anyone know the answer to this question?', 'https://api.dictionaryapi.dev/media/pronunciations/en/anyone-us.mp3'),
('T2', 'somewhere', 'I left my keys somewhere in the room.', 'https://api.dictionaryapi.dev/media/pronunciations/en/somewhere-us.mp3'),
('T2', 'nowhere', 'The missing book was nowhere to be found.', 'https://api.dictionaryapi.dev/media/pronunciations/en/nowhere-us.mp3'),
('T2', 'became a mathematician', 'She studied hard and became a mathematician.', 'https://api.dictionaryapi.dev/media/pronunciations/en/became-us.mp3'),
('T2', 'left medical school', 'He left medical school to pursue music.', 'https://api.dictionaryapi.dev/media/pronunciations/en/left-us.mp3'),
('T2', 'taught people', 'The professor taught people about history.', 'https://api.dictionaryapi.dev/media/pronunciations/en/taught-us.mp3'),
('T2', 'wrote one more book', 'The famous author wrote one more book before retiring.', 'https://api.dictionaryapi.dev/media/pronunciations/en/wrote-us.mp3'),
('T2', 'began to use the telescope', 'Galileo began to use the telescope to study space.', 'https://api.dictionaryapi.dev/media/pronunciations/en/began-us.mp3'),
('T2', 'made important discoveries', 'Scientists made important discoveries in medicine.', 'https://api.dictionaryapi.dev/media/pronunciations/en/made-us.mp3'),
('T2', 'tumble dryer', 'Put the wet clothes into the tumble dryer.', 'https://api.dictionaryapi.dev/media/pronunciations/en/tumble-us.mp3'),
('T2', 'blender', 'We use the blender to make fruit smoothies.', 'https://api.dictionaryapi.dev/media/pronunciations/en/blender-us.mp3'),
('T2', 'heater', 'Turn on the heater because it is cold inside.', 'https://api.dictionaryapi.dev/media/pronunciations/en/heater-us.mp3'),
('T2', 'iron', 'She used an iron to smooth her shirt.', 'https://api.dictionaryapi.dev/media/pronunciations/en/iron-us.mp3'),
('T2', 'water purifier', 'Drink fresh water from the water purifier.', 'https://api.dictionaryapi.dev/media/pronunciations/en/water-us.mp3'),
('T2', 'toaster', 'I put two slices of bread in the toaster.', 'https://api.dictionaryapi.dev/media/pronunciations/en/toaster-us.mp3'),
('T2', 'remote control', 'Pass me the remote control to change the TV channel.', 'https://api.dictionaryapi.dev/media/pronunciations/en/remote-us.mp3'),
('T2', 'keyboard', 'He typed his assignment on the computer keyboard.', 'https://api.dictionaryapi.dev/media/pronunciations/en/keyboard-us.mp3'),
('T2', 'broke his arm', 'He fell off his bike and broke his arm.', 'https://api.dictionaryapi.dev/media/pronunciations/en/broke-us.mp3'),
('T2', 'burnt his finger', 'He touched the hot stove and burnt his finger.', 'https://api.dictionaryapi.dev/media/pronunciations/en/burnt-us.mp3'),
('T2', 'cut her finger', 'She cut her finger while chopping vegetables.', 'https://api.dictionaryapi.dev/media/pronunciations/en/cut-us.mp3'),
('T2', 'sprained her ankle', 'She sprained her ankle while playing soccer.', 'https://api.dictionaryapi.dev/media/pronunciations/en/sprained-us.mp3'),
('T2', 'slipped and fell', 'He slipped and fell on the icy sidewalk.', 'https://api.dictionaryapi.dev/media/pronunciations/en/slipped-us.mp3'),
('T2', 'hit his head', 'He bumped into the doorframe and hit his head.', 'https://api.dictionaryapi.dev/media/pronunciations/en/hit-us.mp3'),
('T2', 'She was reading.', 'She was reading.', 'https://api.dictionaryapi.dev/media/pronunciations/en/she-us.mp3'),
('T2', 'They were watching.', 'They were watching.', 'https://api.dictionaryapi.dev/media/pronunciations/en/they-us.mp3'),
('T2', 'He was walking.', 'He was walking.', 'https://api.dictionaryapi.dev/media/pronunciations/en/he-us.mp3'),
('T2', 'straight', 'Walk straight down this hallway.', 'https://api.dictionaryapi.dev/media/pronunciations/en/straight-us.mp3'),
('T2', 'cross', 'Cross the road at the pedestrian crossing.', 'https://api.dictionaryapi.dev/media/pronunciations/en/cross-us.mp3'),
('T2', 'right', 'Turn right at the traffic lights.', 'https://api.dictionaryapi.dev/media/pronunciations/en/right-us.mp3'),
('T2', 'left', 'Take a left turn after the gas station.', 'https://api.dictionaryapi.dev/media/pronunciations/en/left-us.mp3'),
('T2', 'corner', 'Wait for me at the corner of the street.', 'https://api.dictionaryapi.dev/media/pronunciations/en/corner-us.mp3'),
('T2', 'across', 'The store is across the street.', 'https://api.dictionaryapi.dev/media/pronunciations/en/across-us.mp3'),
('T2', 'near', 'Our house is near the school.', 'https://api.dictionaryapi.dev/media/pronunciations/en/near-us.mp3'),
('T2', 'away', 'The birds flew away to the south.', 'https://api.dictionaryapi.dev/media/pronunciations/en/away-us.mp3'),
('T2', 'around', 'We walked around the town square.', 'https://api.dictionaryapi.dev/media/pronunciations/en/around-us.mp3'),
('T2', 'became', 'He became the new class representative.', 'https://api.dictionaryapi.dev/media/pronunciations/en/became-us.mp3'),
('T2', 'taught', 'She taught math for twenty years.', 'https://api.dictionaryapi.dev/media/pronunciations/en/taught-us.mp3'),
('T2', 'wrote', 'He wrote a letter to his friend.', 'https://api.dictionaryapi.dev/media/pronunciations/en/wrote-us.mp3'),
('T2', 'began', 'The concert began right on schedule.', 'https://api.dictionaryapi.dev/media/pronunciations/en/began-us.mp3'),
('T2', 'made', 'They made a delicious cake.', 'https://api.dictionaryapi.dev/media/pronunciations/en/made-us.mp3'),
('T2', 'broke', 'He accidentally broke the glass window.', 'https://api.dictionaryapi.dev/media/pronunciations/en/broke-us.mp3'),
('T2', 'burnt', 'The toast was burnt after staying too long in the oven.', 'https://api.dictionaryapi.dev/media/pronunciations/en/burnt-us.mp3'),
('T2', 'sprained', 'She sprained her wrist during gymnastics.', 'https://api.dictionaryapi.dev/media/pronunciations/en/sprained-us.mp3'),
('T2', 'slipped', 'He slipped on the wet bathroom floor.', 'https://api.dictionaryapi.dev/media/pronunciations/en/slipped-us.mp3'),
('T2', 'sweeter', 'Honey is sweeter than sugar.', 'https://api.dictionaryapi.dev/media/pronunciations/en/sweeter-us.mp3'),
('T2', 'busier', 'The city center is busier during peak hours.', 'https://api.dictionaryapi.dev/media/pronunciations/en/busier-us.mp3'),
('T2', 'dangerous', 'Skydiving can be dangerous.', 'https://api.dictionaryapi.dev/media/pronunciations/en/dangerous-us.mp3'),
('T2', 'badly', 'He played badly in the second half.', 'https://api.dictionaryapi.dev/media/pronunciations/en/badly-us.mp3'),
('T2', 'make fun', 'Do not make fun of others.', 'https://api.dictionaryapi.dev/media/pronunciations/en/make-us.mp3'),
('T2', 'started', 'The game started on time.', 'https://api.dictionaryapi.dev/media/pronunciations/en/started-us.mp3'),
('T2', 'worked', 'He worked hard all week.', 'https://api.dictionaryapi.dev/media/pronunciations/en/worked-us.mp3'),
('T2', 'universe', 'The universe is vast and mysterious.', 'https://api.dictionaryapi.dev/media/pronunciations/en/universe-us.mp3'),
('T2', 'world', 'Travel opens your eyes to the world.', 'https://api.dictionaryapi.dev/media/pronunciations/en/world-us.mp3'),
('T2', 'earth', 'We must protect planet Earth.', 'https://api.dictionaryapi.dev/media/pronunciations/en/earth-us.mp3'),
('T2', 'largest', 'Jupiter is the largest planet in our solar system.', 'https://api.dictionaryapi.dev/media/pronunciations/en/largest-us.mp3'),
('T2', 'heaviest', 'Blue whales are the heaviest animals on Earth.', 'https://api.dictionaryapi.dev/media/pronunciations/en/heaviest-us.mp3'),
('T2', 'least', 'That was the least difficult question.', 'https://api.dictionaryapi.dev/media/pronunciations/en/least-us.mp3'),
('T2', 'expensive', 'That luxury car is very expensive.', 'https://api.dictionaryapi.dev/media/pronunciations/en/expensive-us.mp3'),
('T2', 'furthest', 'Neptune is the furthest planet from the Sun.', 'https://api.dictionaryapi.dev/media/pronunciations/en/furthest-us.mp3'),
('T2', 'worst', 'That was the worst storm of the season.', 'https://api.dictionaryapi.dev/media/pronunciations/en/worst-us.mp3'),
('T2', 'felt', 'She felt happy after receiving the good news.', 'https://api.dictionaryapi.dev/media/pronunciations/en/felt-us.mp3');
