-- ============================================================
-- SCRIPT SQL: INSERÇÃO DAS PALAVRAS E FRASES DO ESTÁGIO T1
-- Tabela: public.palavras_spelling
-- Nível: T1 (130 itens únicos deduplicados)
-- Execute este script no SQL Editor do Supabase
-- ============================================================

-- Remover registros anteriores de nível T1 (opcional, para recarga limpa)
DELETE FROM public.palavras_spelling WHERE level = 'T1';

INSERT INTO public.palavras_spelling (level, word, sentence, audio_url) VALUES
('T1', 'bear', 'A polar bear can swim for miles.', 'https://api.dictionaryapi.dev/media/pronunciations/en/bear-us.mp3'),
('T1', 'cow', 'The farmer milks the cow every morning.', 'https://api.dictionaryapi.dev/media/pronunciations/en/cow-us.mp3'),
('T1', 'dolphin', 'The dolphin jumped gracefully out of the water.', 'https://api.dictionaryapi.dev/media/pronunciations/en/dolphin-us.mp3'),
('T1', 'eagle', 'The eagle flew high above the mountains.', 'https://api.dictionaryapi.dev/media/pronunciations/en/eagle-us.mp3'),
('T1', 'frog', 'A green frog sat on a lily pad.', 'https://api.dictionaryapi.dev/media/pronunciations/en/frog-us.mp3'),
('T1', 'goat', 'The mountain goat climbed up the rocky hill.', 'https://api.dictionaryapi.dev/media/pronunciations/en/goat-us.mp3'),
('T1', 'peacock', 'The peacock showed its colorful feathers.', 'https://api.dictionaryapi.dev/media/pronunciations/en/peacock-us.mp3'),
('T1', 'shark', 'A great white shark swam through the ocean.', 'https://api.dictionaryapi.dev/media/pronunciations/en/shark-us.mp3'),
('T1', 'turtle', 'The sea turtle laid her eggs on the beach.', 'https://api.dictionaryapi.dev/media/pronunciations/en/turtle-us.mp3'),
('T1', 'noisy', 'The city street was very noisy.', 'https://api.dictionaryapi.dev/media/pronunciations/en/noisy-us.mp3'),
('T1', 'light', 'Feathers are extremely light.', 'https://api.dictionaryapi.dev/media/pronunciations/en/light-us.mp3'),
('T1', 'heavier', 'An elephant is much heavier than a horse.', 'https://api.dictionaryapi.dev/media/pronunciations/en/heavier-us.mp3'),
('T1', 'difficult', 'Solving this math puzzle was difficult.', 'https://api.dictionaryapi.dev/media/pronunciations/en/difficult-us.mp3'),
('T1', 'friendly', 'Our new classmate is very friendly.', 'https://api.dictionaryapi.dev/media/pronunciations/en/friendly-us.mp3'),
('T1', 'slower', 'Turtles are slower than hares.', 'https://api.dictionaryapi.dev/media/pronunciations/en/slower-us.mp3'),
('T1', 'have a party', 'We plan to have a party on Saturday.', 'https://api.dictionaryapi.dev/media/pronunciations/en/have-us.mp3'),
('T1', 'read a text', 'Students must read a text carefully before answering.', 'https://api.dictionaryapi.dev/media/pronunciations/en/read-us.mp3'),
('T1', 'foggy', 'The morning was so foggy that we could hardly see.', 'https://api.dictionaryapi.dev/media/pronunciations/en/foggy-us.mp3'),
('T1', 'snowy', 'Kids love playing outside on a snowy day.', 'https://api.dictionaryapi.dev/media/pronunciations/en/snowy-us.mp3'),
('T1', 'windy', 'Hold onto your hat because it is very windy.', 'https://api.dictionaryapi.dev/media/pronunciations/en/windy-us.mp3'),
('T1', 'limousine driver', 'The limousine driver opened the car door for us.', 'https://api.dictionaryapi.dev/media/pronunciations/en/limousine-us.mp3'),
('T1', 'businessperson', 'A successful businessperson attends international conferences.', 'https://api.dictionaryapi.dev/media/pronunciations/en/businessperson-us.mp3'),
('T1', 'engineer', 'An engineer designed the new bridge.', 'https://api.dictionaryapi.dev/media/pronunciations/en/engineer-us.mp3'),
('T1', 'lawyer', 'The lawyer presented evidence in court.', 'https://api.dictionaryapi.dev/media/pronunciations/en/lawyer-us.mp3'),
('T1', 'nurse', 'A nurse took care of the patients at the hospital.', 'https://api.dictionaryapi.dev/media/pronunciations/en/nurse-us.mp3'),
('T1', 'sales person', 'The salesperson explained the product features.', 'https://api.dictionaryapi.dev/media/pronunciations/en/sales-us.mp3'),
('T1', 'waitress', 'The waitress brought our meals to the table.', 'https://api.dictionaryapi.dev/media/pronunciations/en/waitress-us.mp3'),
('T1', 'woke up', 'I woke up early this morning.', 'https://api.dictionaryapi.dev/media/pronunciations/en/woke-us.mp3'),
('T1', 'had', 'We had breakfast together.', 'https://api.dictionaryapi.dev/media/pronunciations/en/had-us.mp3'),
('T1', 'ate', 'She ate a delicious sandwich.', 'https://api.dictionaryapi.dev/media/pronunciations/en/ate-us.mp3'),
('T1', 'bought', 'He bought a new jacket.', 'https://api.dictionaryapi.dev/media/pronunciations/en/bought-us.mp3'),
('T1', 'took', 'They took lots of photos during the trip.', 'https://api.dictionaryapi.dev/media/pronunciations/en/took-us.mp3'),
('T1', 'went', 'Our family went to the beach.', 'https://api.dictionaryapi.dev/media/pronunciations/en/went-us.mp3'),
('T1', 'saw', 'I saw a beautiful bird in the tree.', 'https://api.dictionaryapi.dev/media/pronunciations/en/saw-us.mp3'),
('T1', 'yesterday', 'I visited my grandparents yesterday.', 'https://api.dictionaryapi.dev/media/pronunciations/en/yesterday-us.mp3'),
('T1', 'ago', 'They arrived two hours ago.', 'https://api.dictionaryapi.dev/media/pronunciations/en/ago-us.mp3'),
('T1', 'arrived', 'The train arrived right on time.', 'https://api.dictionaryapi.dev/media/pronunciations/en/arrived-us.mp3'),
('T1', 'stayed', 'We stayed at a comfortable hotel.', 'https://api.dictionaryapi.dev/media/pronunciations/en/stayed-us.mp3'),
('T1', 'studied', 'She studied hard for her exams.', 'https://api.dictionaryapi.dev/media/pronunciations/en/studied-us.mp3'),
('T1', 'worked', 'My father worked at the bank for ten years.', 'https://api.dictionaryapi.dev/media/pronunciations/en/worked-us.mp3'),
('T1', 'tried', 'He tried his best to win the race.', 'https://api.dictionaryapi.dev/media/pronunciations/en/tried-us.mp3'),
('T1', 'eraser', 'Use an eraser to fix your mistake.', 'https://api.dictionaryapi.dev/media/pronunciations/en/eraser-us.mp3'),
('T1', 'highlighter', 'Use a yellow highlighter to mark important points.', 'https://api.dictionaryapi.dev/media/pronunciations/en/highlighter-us.mp3'),
('T1', 'mechanical pencil', 'A mechanical pencil is great for drawing precise lines.', 'https://api.dictionaryapi.dev/media/pronunciations/en/mechanical-us.mp3'),
('T1', 'notepad', 'Write down the phone number on a notepad.', 'https://api.dictionaryapi.dev/media/pronunciations/en/notepad-us.mp3'),
('T1', 'piece of paper', 'Can I borrow a piece of paper?', 'https://api.dictionaryapi.dev/media/pronunciations/en/piece-us.mp3'),
('T1', 'ruler', 'Use a ruler to draw straight lines.', 'https://api.dictionaryapi.dev/media/pronunciations/en/ruler-us.mp3'),
('T1', 'sharpener', 'My pencil broke so I need a sharpener.', 'https://api.dictionaryapi.dev/media/pronunciations/en/sharpener-us.mp3'),
('T1', 'stapler', 'Use a stapler to attach these documents together.', 'https://api.dictionaryapi.dev/media/pronunciations/en/stapler-us.mp3'),
('T1', 'sticker', 'The teacher gave me a star sticker for good work.', 'https://api.dictionaryapi.dev/media/pronunciations/en/sticker-us.mp3'),
('T1', 'pencil case', 'Keep all your pens safe in your pencil case.', 'https://api.dictionaryapi.dev/media/pronunciations/en/pencil-us.mp3'),
('T1', 'police station', 'Report the lost wallet at the police station.', 'https://api.dictionaryapi.dev/media/pronunciations/en/police-us.mp3'),
('T1', 'restaurant', 'We had dinner at an Italian restaurant.', 'https://api.dictionaryapi.dev/media/pronunciations/en/restaurant-us.mp3'),
('T1', 'hospital', 'Doctors work hard at the city hospital.', 'https://api.dictionaryapi.dev/media/pronunciations/en/hospital-us.mp3'),
('T1', 'supermarket', 'Mom bought fresh fruits at the supermarket.', 'https://api.dictionaryapi.dev/media/pronunciations/en/supermarket-us.mp3'),
('T1', 'bakery', 'The fresh bread from the bakery smells delicious.', 'https://api.dictionaryapi.dev/media/pronunciations/en/bakery-us.mp3'),
('T1', 'beauty salon', 'She went to the beauty salon to get her hair cut.', 'https://api.dictionaryapi.dev/media/pronunciations/en/beauty-us.mp3'),
('T1', 'library', 'Students study quietly in the school library.', 'https://api.dictionaryapi.dev/media/pronunciations/en/library-us.mp3'),
('T1', 'bookshop', 'I bought a novel at the local bookshop.', 'https://api.dictionaryapi.dev/media/pronunciations/en/bookshop-us.mp3'),
('T1', 'post office', 'Mail your letter at the post office.', 'https://api.dictionaryapi.dev/media/pronunciations/en/post-us.mp3'),
('T1', 'drugstore', 'Buy medicine at the nearby drugstore.', 'https://api.dictionaryapi.dev/media/pronunciations/en/drugstore-us.mp3'),
('T1', 'gym', 'He goes to the gym three times a week.', 'https://api.dictionaryapi.dev/media/pronunciations/en/gym-us.mp3'),
('T1', 'museum', 'The natural history museum has dinosaur bones.', 'https://api.dictionaryapi.dev/media/pronunciations/en/museum-us.mp3'),
('T1', 'theatre', 'We bought tickets to see a play at the theatre.', 'https://api.dictionaryapi.dev/media/pronunciations/en/theatre-us.mp3'),
('T1', 'homework', 'Don''t forget to finish your homework.', 'https://api.dictionaryapi.dev/media/pronunciations/en/homework-us.mp3'),
('T1', 'sent', 'He sent me a friendly message.', 'https://api.dictionaryapi.dev/media/pronunciations/en/sent-us.mp3'),
('T1', 'read a book', 'I read a book before going to sleep.', 'https://api.dictionaryapi.dev/media/pronunciations/en/read-us.mp3'),
('T1', 'slept', 'The baby slept soundly all night.', 'https://api.dictionaryapi.dev/media/pronunciations/en/slept-us.mp3'),
('T1', 'spent', 'We spent the afternoon playing games.', 'https://api.dictionaryapi.dev/media/pronunciations/en/spent-us.mp3'),
('T1', 'wrote', 'She wrote a letter to her grandmother.', 'https://api.dictionaryapi.dev/media/pronunciations/en/wrote-us.mp3'),
('T1', 'lost', 'He lost his keys in the garden.', 'https://api.dictionaryapi.dev/media/pronunciations/en/lost-us.mp3'),
('T1', 'gave', 'My parents gave me a wonderful gift.', 'https://api.dictionaryapi.dev/media/pronunciations/en/gave-us.mp3'),
('T1', 'watched', 'They watched the fireworks at midnight.', 'https://api.dictionaryapi.dev/media/pronunciations/en/watched-us.mp3'),
('T1', 'travelled', 'She travelled to Japan last summer.', 'https://api.dictionaryapi.dev/media/pronunciations/en/travelled-us.mp3'),
('T1', 'an eraser', 'Use an eraser to fix your mistake.', 'https://api.dictionaryapi.dev/media/pronunciations/en/eraser-us.mp3'),
('T1', 'a highlighter', 'Use a yellow highlighter to mark important points.', 'https://api.dictionaryapi.dev/media/pronunciations/en/highlighter-us.mp3'),
('T1', 'some lead', 'I need some lead for my automatic pencil.', 'https://api.dictionaryapi.dev/media/pronunciations/en/lead-us.mp3'),
('T1', 'a mechanical pencil', 'A mechanical pencil is great for drawing precise lines.', 'https://api.dictionaryapi.dev/media/pronunciations/en/mechanical-us.mp3'),
('T1', 'a notepad', 'Write down the phone number on a notepad.', 'https://api.dictionaryapi.dev/media/pronunciations/en/notepad-us.mp3'),
('T1', 'a piece of paper', 'Can I borrow a piece of paper?', 'https://api.dictionaryapi.dev/media/pronunciations/en/piece-us.mp3'),
('T1', 'a post-it note', 'She left a post-it note on the refrigerator.', 'https://api.dictionaryapi.dev/media/pronunciations/en/postit-us.mp3'),
('T1', 'a ruler', 'Use a ruler to draw straight lines.', 'https://api.dictionaryapi.dev/media/pronunciations/en/ruler-us.mp3'),
('T1', 'a sharpener', 'My pencil broke so I need a sharpener.', 'https://api.dictionaryapi.dev/media/pronunciations/en/sharpener-us.mp3'),
('T1', 'a stapler', 'Use a stapler to attach these documents together.', 'https://api.dictionaryapi.dev/media/pronunciations/en/stapler-us.mp3'),
('T1', 'a sticker', 'The teacher gave me a star sticker for good work.', 'https://api.dictionaryapi.dev/media/pronunciations/en/sticker-us.mp3'),
('T1', 'a pencil case', 'Keep all your pens safe in your pencil case.', 'https://api.dictionaryapi.dev/media/pronunciations/en/pencil-us.mp3'),
('T1', 'Kevin was at home.', 'Kevin was at home.', 'https://api.dictionaryapi.dev/media/pronunciations/en/kevin-us.mp3'),
('T1', 'They were at school.', 'They were at school.', 'https://api.dictionaryapi.dev/media/pronunciations/en/they-us.mp3'),
('T1', 'Who was he?', 'Who was he?', 'https://api.dictionaryapi.dev/media/pronunciations/en/who-us.mp3'),
('T1', 'Where were they?', 'Where were they?', 'https://api.dictionaryapi.dev/media/pronunciations/en/where-us.mp3'),
('T1', 'Yes, I was.', 'Yes, I was.', 'https://api.dictionaryapi.dev/media/pronunciations/en/yes-us.mp3'),
('T1', 'No, we weren''t.', 'No, we weren''t.', 'https://api.dictionaryapi.dev/media/pronunciations/en/no-us.mp3'),
('T1', 'didn''t do her homework', 'She didn''t do her homework so the teacher called her parents.', 'https://api.dictionaryapi.dev/media/pronunciations/en/didnt-us.mp3'),
('T1', 'got a bad mark', 'He was sad because he got a bad mark.', 'https://api.dictionaryapi.dev/media/pronunciations/en/got-us.mp3'),
('T1', 'sent an email', 'I sent an email to the customer support.', 'https://api.dictionaryapi.dev/media/pronunciations/en/sent-us.mp3'),
('T1', 'slept for three hours', 'He only slept for three hours last night.', 'https://api.dictionaryapi.dev/media/pronunciations/en/slept-us.mp3'),
('T1', 'spent Sunday in my room', 'I spent Sunday in my room reading comics.', 'https://api.dictionaryapi.dev/media/pronunciations/en/spent-us.mp3'),
('T1', 'wrote a note', 'She wrote a note to remind herself.', 'https://api.dictionaryapi.dev/media/pronunciations/en/wrote-us.mp3'),
('T1', 'lost concentration', 'He lost concentration during the long lecture.', 'https://api.dictionaryapi.dev/media/pronunciations/en/lost-us.mp3'),
('T1', 'gave a present', 'They gave a present to the birthday girl.', 'https://api.dictionaryapi.dev/media/pronunciations/en/gave-us.mp3'),
('T1', 'watched a funny film', 'We watched a funny film and laughed a lot.', 'https://api.dictionaryapi.dev/media/pronunciations/en/watched-us.mp3'),
('T1', 'travelled to Europe', 'Our neighbors travelled to Europe last month.', 'https://api.dictionaryapi.dev/media/pronunciations/en/travelled-us.mp3'),
('T1', 'didn''t do', 'He didn''t do his chores today.', 'https://api.dictionaryapi.dev/media/pronunciations/en/didnt-us.mp3'),
('T1', 'didn''t see', 'I didn''t see where you parked the car.', 'https://api.dictionaryapi.dev/media/pronunciations/en/didnt-us.mp3'),
('T1', 'Did you go to school?', 'Did you go to school?', 'https://api.dictionaryapi.dev/media/pronunciations/en/did-us.mp3'),
('T1', 'What did she do?', 'What did she do?', 'https://api.dictionaryapi.dev/media/pronunciations/en/what-us.mp3'),
('T1', 'Yes, we did.', 'Yes, we did.', 'https://api.dictionaryapi.dev/media/pronunciations/en/yes-us.mp3'),
('T1', 'No, we didn''t.', 'No, we didn''t.', 'https://api.dictionaryapi.dev/media/pronunciations/en/no-us.mp3'),
('T1', 'last Thursday', 'Our soccer team won the match last Thursday.', 'https://api.dictionaryapi.dev/media/pronunciations/en/last-us.mp3'),
('T1', 'Was it difficult?', 'Was it difficult to pass the driving test?', 'https://api.dictionaryapi.dev/media/pronunciations/en/was-us.mp3'),
('T1', 'more difficult than', 'Physics is more difficult than geography.', 'https://api.dictionaryapi.dev/media/pronunciations/en/more-us.mp3'),
('T1', 'slower than', 'Walking is slower than riding a bike.', 'https://api.dictionaryapi.dev/media/pronunciations/en/slower-us.mp3'),
('T1', 'take an Uber', 'It was raining so we decided to take an Uber.', 'https://api.dictionaryapi.dev/media/pronunciations/en/take-us.mp3'),
('T1', 'going to school', 'She loves going to school to see her friends.', 'https://api.dictionaryapi.dev/media/pronunciations/en/going-us.mp3'),
('T1', 'listening to music', 'He enjoys listening to music while studying.', 'https://api.dictionaryapi.dev/media/pronunciations/en/listening-us.mp3'),
('T1', 'taking a shower', 'Taking a warm shower helps me relax.', 'https://api.dictionaryapi.dev/media/pronunciations/en/taking-us.mp3'),
('T1', 'watching Netflix', 'They spent Friday evening watching Netflix.', 'https://api.dictionaryapi.dev/media/pronunciations/en/watching-us.mp3'),
('T1', 'a limousine drive', 'They took a limousine drive to the concert.', 'https://api.dictionaryapi.dev/media/pronunciations/en/limousine-us.mp3'),
('T1', 'a businessperson', 'A successful businessperson attends international conferences.', 'https://api.dictionaryapi.dev/media/pronunciations/en/businessperson-us.mp3'),
('T1', 'an engineer', 'An engineer designed the new bridge.', 'https://api.dictionaryapi.dev/media/pronunciations/en/engineer-us.mp3'),
('T1', 'a lawyer', 'The lawyer presented evidence in court.', 'https://api.dictionaryapi.dev/media/pronunciations/en/lawyer-us.mp3'),
('T1', 'a nurse', 'A nurse took care of the patients at the hospital.', 'https://api.dictionaryapi.dev/media/pronunciations/en/nurse-us.mp3'),
('T1', 'a salesperson', 'The salesperson explained the product features.', 'https://api.dictionaryapi.dev/media/pronunciations/en/salesperson-us.mp3'),
('T1', 'a waitress', 'The waitress brought our meals to the table.', 'https://api.dictionaryapi.dev/media/pronunciations/en/waitress-us.mp3'),
('T1', 'the day before yesterday', 'I saw him the day before yesterday.', 'https://api.dictionaryapi.dev/media/pronunciations/en/the-us.mp3'),
('T1', 'five months ago', 'She started learning English five months ago.', 'https://api.dictionaryapi.dev/media/pronunciations/en/five-us.mp3'),
('T1', 'last night', 'We watched a great movie last night.', 'https://api.dictionaryapi.dev/media/pronunciations/en/last-us.mp3'),
('T1', 'yesterday morning', 'It rained heavily yesterday morning.', 'https://api.dictionaryapi.dev/media/pronunciations/en/yesterday-us.mp3'),
('T1', 'didn''t watch', 'I didn''t watch TV last night.', 'https://api.dictionaryapi.dev/media/pronunciations/en/didnt-us.mp3'),
('T1', 'didn''t want', 'She didn''t want to leave the park.', 'https://api.dictionaryapi.dev/media/pronunciations/en/didnt-us.mp3');
