-- ============================================================
-- SCRIPT SQL: INSERÇÃO DAS PALAVRAS E FRASES DO ESTÁGIO J1
-- Tabela: public.palavras_spelling
-- Nível: J1 (118 itens únicos deduplicados)
-- Execute este script no SQL Editor do Supabase
-- ============================================================

-- Remover registros anteriores de nível J1 (opcional, para recarga limpa)
DELETE FROM public.palavras_spelling WHERE level = 'J1';

INSERT INTO public.palavras_spelling (level, word, sentence, audio_url) VALUES
('J1', 'one', 'I have one dog.', 'https://api.dictionaryapi.dev/media/pronunciations/en/one-us.mp3'),
('J1', 'black', 'The night sky is black.', 'https://api.dictionaryapi.dev/media/pronunciations/en/black-us.mp3'),
('J1', 'two', 'She has two cats.', 'https://api.dictionaryapi.dev/media/pronunciations/en/two-us.mp3'),
('J1', 'orange', 'Carrots are orange.', 'https://api.dictionaryapi.dev/media/pronunciations/en/orange-us.mp3'),
('J1', 'three', 'There are three apples on the table.', 'https://api.dictionaryapi.dev/media/pronunciations/en/three-us.mp3'),
('J1', 'brown', 'Bears have brown fur.', 'https://api.dictionaryapi.dev/media/pronunciations/en/brown-us.mp3'),
('J1', 'four', 'A chair has four legs.', 'https://api.dictionaryapi.dev/media/pronunciations/en/four-us.mp3'),
('J1', 'white', 'Snow is cold and white.', 'https://api.dictionaryapi.dev/media/pronunciations/en/white-us.mp3'),
('J1', 'five', 'Give me a high five!', 'https://api.dictionaryapi.dev/media/pronunciations/en/five-us.mp3'),
('J1', 'yellow', 'The sun is bright yellow.', 'https://api.dictionaryapi.dev/media/pronunciations/en/yellow-us.mp3'),
('J1', 'eight', 'An octopus has eight legs.', 'https://api.dictionaryapi.dev/media/pronunciations/en/eight-us.mp3'),
('J1', 'green', 'Grass is green in spring.', 'https://api.dictionaryapi.dev/media/pronunciations/en/green-us.mp3'),
('J1', 'T-shirt', 'I bought a white T-shirt.', 'https://api.dictionaryapi.dev/media/pronunciations/en/tshirt-us.mp3'),
('J1', 'eleven', 'Soccer teams have eleven players.', 'https://api.dictionaryapi.dev/media/pronunciations/en/eleven-us.mp3'),
('J1', 'purple', 'Grapes can be purple.', 'https://api.dictionaryapi.dev/media/pronunciations/en/purple-us.mp3'),
('J1', 'crayon', 'Color the picture with a crayon.', 'https://api.dictionaryapi.dev/media/pronunciations/en/crayon-us.mp3'),
('J1', 'twelve', 'There are twelve months in a year.', 'https://api.dictionaryapi.dev/media/pronunciations/en/twelve-us.mp3'),
('J1', 'red', 'A strawberry is red.', 'https://api.dictionaryapi.dev/media/pronunciations/en/red-us.mp3'),
('J1', 'bike', 'I ride my bike in the park.', 'https://api.dictionaryapi.dev/media/pronunciations/en/bike-us.mp3'),
('J1', 'thirteen', 'Thirteen is my lucky number.', 'https://api.dictionaryapi.dev/media/pronunciations/en/thirteen-us.mp3'),
('J1', 'blue', 'The ocean is deep blue.', 'https://api.dictionaryapi.dev/media/pronunciations/en/blue-us.mp3'),
('J1', 'bag', 'Pack your school bag for tomorrow.', 'https://api.dictionaryapi.dev/media/pronunciations/en/bag-us.mp3'),
('J1', 'fourteen', 'He is fourteen years old.', 'https://api.dictionaryapi.dev/media/pronunciations/en/fourteen-us.mp3'),
('J1', 'grey', 'Elephants are big and grey.', 'https://api.dictionaryapi.dev/media/pronunciations/en/grey-us.mp3'),
('J1', 'chair', 'Sit on the chair comfortably.', 'https://api.dictionaryapi.dev/media/pronunciations/en/chair-us.mp3'),
('J1', 'fifteen', 'We have a fifteen minute break.', 'https://api.dictionaryapi.dev/media/pronunciations/en/fifteen-us.mp3'),
('J1', 'pink', 'Flamingos are pink birds.', 'https://api.dictionaryapi.dev/media/pronunciations/en/pink-us.mp3'),
('J1', 'sofa', 'The sofa is very soft.', 'https://api.dictionaryapi.dev/media/pronunciations/en/sofa-us.mp3'),
('J1', 'sixteen', 'She turns sixteen today.', 'https://api.dictionaryapi.dev/media/pronunciations/en/sixteen-us.mp3'),
('J1', 'watch', 'He wears a gold watch.', 'https://api.dictionaryapi.dev/media/pronunciations/en/watch-us.mp3'),
('J1', 'seventeen', 'There are seventeen students in class.', 'https://api.dictionaryapi.dev/media/pronunciations/en/seventeen-us.mp3'),
('J1', 'eraser', 'Erase the line with an eraser.', 'https://api.dictionaryapi.dev/media/pronunciations/en/eraser-us.mp3'),
('J1', 'nineteen', 'Room nineteen is on the second floor.', 'https://api.dictionaryapi.dev/media/pronunciations/en/nineteen-us.mp3'),
('J1', 'elephant', 'An elephant has big ears.', 'https://api.dictionaryapi.dev/media/pronunciations/en/elephant-us.mp3'),
('J1', 'twenty', 'I counted twenty birds in the sky.', 'https://api.dictionaryapi.dev/media/pronunciations/en/twenty-us.mp3'),
('J1', 'ice cream', 'I love strawberry ice cream on hot days.', 'https://api.dictionaryapi.dev/media/pronunciations/en/ice-us.mp3'),
('J1', 'brother', 'My brother plays video games with me.', 'https://api.dictionaryapi.dev/media/pronunciations/en/brother-us.mp3'),
('J1', 'umbrella', 'Take an umbrella because it is raining.', 'https://api.dictionaryapi.dev/media/pronunciations/en/umbrella-us.mp3'),
('J1', 'sister', 'My sister helps me with homework.', 'https://api.dictionaryapi.dev/media/pronunciations/en/sister-us.mp3'),
('J1', 'horse', 'The horse ran across the field.', 'https://api.dictionaryapi.dev/media/pronunciations/en/horse-us.mp3'),
('J1', 'grandfather', 'My grandfather tells great stories.', 'https://api.dictionaryapi.dev/media/pronunciations/en/grandfather-us.mp3'),
('J1', 'cow', 'The cow gives us fresh milk.', 'https://api.dictionaryapi.dev/media/pronunciations/en/cow-us.mp3'),
('J1', 'grandmother', 'My grandmother bakes delicious cookies.', 'https://api.dictionaryapi.dev/media/pronunciations/en/grandmother-us.mp3'),
('J1', 'apple', 'An apple a day keeps the doctor away.', 'https://api.dictionaryapi.dev/media/pronunciations/en/apple-us.mp3'),
('J1', 'dad', 'My dad drives me to school.', 'https://api.dictionaryapi.dev/media/pronunciations/en/dad-us.mp3'),
('J1', 'sitting room', 'We watch TV in the sitting room.', 'https://api.dictionaryapi.dev/media/pronunciations/en/sitting-us.mp3'),
('J1', 'mum', 'My mum gives the best hugs.', 'https://api.dictionaryapi.dev/media/pronunciations/en/mum-us.mp3'),
('J1', 'dining room', 'Our family eats in the dining room.', 'https://api.dictionaryapi.dev/media/pronunciations/en/dining-us.mp3'),
('J1', 'pencil', 'Write your name with a pencil.', 'https://api.dictionaryapi.dev/media/pronunciations/en/pencil-us.mp3'),
('J1', 'bathroom', 'Wash your hands in the bathroom.', 'https://api.dictionaryapi.dev/media/pronunciations/en/bathroom-us.mp3'),
('J1', 'desk', 'Clean your desk before class starts.', 'https://api.dictionaryapi.dev/media/pronunciations/en/desk-us.mp3'),
('J1', 'bedroom', 'My bedroom has a big comfortable bed.', 'https://api.dictionaryapi.dev/media/pronunciations/en/bedroom-us.mp3'),
('J1', 'book', 'Open your English book to page ten.', 'https://api.dictionaryapi.dev/media/pronunciations/en/book-us.mp3'),
('J1', 'kitchen', 'Mom cooks dinner in the kitchen.', 'https://api.dictionaryapi.dev/media/pronunciations/en/kitchen-us.mp3'),
('J1', 'table', 'Put the plates on the dining table.', 'https://api.dictionaryapi.dev/media/pronunciations/en/table-us.mp3'),
('J1', 'garage', 'We park our car in the garage.', 'https://api.dictionaryapi.dev/media/pronunciations/en/garage-us.mp3'),
('J1', 'favourite', 'Pizza is my favourite food.', 'https://api.dictionaryapi.dev/media/pronunciations/en/favourite-us.mp3'),
('J1', 'food', 'Healthy food gives you energy.', 'https://api.dictionaryapi.dev/media/pronunciations/en/food-us.mp3'),
('J1', 'biscuits', 'Chocolate biscuits taste great with milk.', 'https://api.dictionaryapi.dev/media/pronunciations/en/biscuits-us.mp3'),
('J1', 'vegetables', 'Eat your vegetables to stay healthy.', 'https://api.dictionaryapi.dev/media/pronunciations/en/vegetables-us.mp3'),
('J1', 'tomatoes', 'Add some fresh tomatoes to the salad.', 'https://api.dictionaryapi.dev/media/pronunciations/en/tomatoes-us.mp3'),
('J1', 'meat', 'My dog loves to eat meat.', 'https://api.dictionaryapi.dev/media/pronunciations/en/meat-us.mp3'),
('J1', 'sweater', 'Wear a warm sweater in winter.', 'https://api.dictionaryapi.dev/media/pronunciations/en/sweater-us.mp3'),
('J1', 'fish', 'Goldfish swim in water.', 'https://api.dictionaryapi.dev/media/pronunciations/en/fish-us.mp3'),
('J1', 'sunglasses', 'Wear sunglasses on sunny days.', 'https://api.dictionaryapi.dev/media/pronunciations/en/sunglasses-us.mp3'),
('J1', 'bread', 'Pass the fresh bread, please.', 'https://api.dictionaryapi.dev/media/pronunciations/en/bread-us.mp3'),
('J1', 'mobile phone', 'She answered her mobile phone.', 'https://api.dictionaryapi.dev/media/pronunciations/en/mobile-us.mp3'),
('J1', 'rice', 'We eat rice and beans for lunch.', 'https://api.dictionaryapi.dev/media/pronunciations/en/rice-us.mp3'),
('J1', 'stereo', 'Listen to music on the stereo.', 'https://api.dictionaryapi.dev/media/pronunciations/en/stereo-us.mp3'),
('J1', 'trainers', 'Put on your sports trainers to run.', 'https://api.dictionaryapi.dev/media/pronunciations/en/trainers-us.mp3'),
('J1', 'milk', 'Drink a glass of warm milk.', 'https://api.dictionaryapi.dev/media/pronunciations/en/milk-us.mp3'),
('J1', 'jeans', 'He bought a pair of blue jeans.', 'https://api.dictionaryapi.dev/media/pronunciations/en/jeans-us.mp3'),
('J1', 'cheese', 'Mice love eating cheese.', 'https://api.dictionaryapi.dev/media/pronunciations/en/cheese-us.mp3'),
('J1', 'thirty-three', 'The house number is thirty-three.', 'https://api.dictionaryapi.dev/media/pronunciations/en/thirtythree-us.mp3'),
('J1', 'water', 'Drink plenty of water every day.', 'https://api.dictionaryapi.dev/media/pronunciations/en/water-us.mp3'),
('J1', 'forty-four', 'Page forty-four has nice pictures.', 'https://api.dictionaryapi.dev/media/pronunciations/en/fortyfour-us.mp3'),
('J1', 'chicken', 'We had roasted chicken for dinner.', 'https://api.dictionaryapi.dev/media/pronunciations/en/chicken-us.mp3'),
('J1', 'fifty-five', 'My grandmother is fifty-five years old.', 'https://api.dictionaryapi.dev/media/pronunciations/en/fiftyfive-us.mp3'),
('J1', 'yogurt', 'Fruit yogurt is a healthy snack.', 'https://api.dictionaryapi.dev/media/pronunciations/en/yogurt-us.mp3'),
('J1', 'sixty-six', 'Page sixty-six has a nice poem.', 'https://api.dictionaryapi.dev/media/pronunciations/en/sixtysix-us.mp3'),
('J1', 'beans', 'Beans are rich in protein.', 'https://api.dictionaryapi.dev/media/pronunciations/en/beans-us.mp3'),
('J1', 'seventy-seven', 'He scored seventy-seven points.', 'https://api.dictionaryapi.dev/media/pronunciations/en/seventyseven-us.mp3'),
('J1', 'eighty-eight', 'A piano has eighty-eight keys.', 'https://api.dictionaryapi.dev/media/pronunciations/en/eightyeight-us.mp3'),
('J1', 'fruit juice', 'Fresh orange fruit juice is refreshing.', 'https://api.dictionaryapi.dev/media/pronunciations/en/fruit-us.mp3'),
('J1', 'ninety-nine', 'That toy costs ninety-nine cents.', 'https://api.dictionaryapi.dev/media/pronunciations/en/ninety-us.mp3'),
('J1', 'tea', 'My grandma drinks hot tea.', 'https://api.dictionaryapi.dev/media/pronunciations/en/tea-us.mp3'),
('J1', 'one hundred', 'I can count up to one hundred.', 'https://api.dictionaryapi.dev/media/pronunciations/en/one-us.mp3'),
('J1', 'breakfast', 'Breakfast is the most important meal.', 'https://api.dictionaryapi.dev/media/pronunciations/en/breakfast-us.mp3'),
('J1', 'pasta', 'Italian pasta is delicious.', 'https://api.dictionaryapi.dev/media/pronunciations/en/pasta-us.mp3'),
('J1', 'lunch', 'We eat lunch at noon.', 'https://api.dictionaryapi.dev/media/pronunciations/en/lunch-us.mp3'),
('J1', 'dinner', 'Our family gathers for dinner at seven.', 'https://api.dictionaryapi.dev/media/pronunciations/en/dinner-us.mp3'),
('J1', 'hot dog', 'I ordered a hot dog at the stadium.', 'https://api.dictionaryapi.dev/media/pronunciations/en/hot-us.mp3'),
('J1', 'chocolate cake', 'She baked a chocolate cake for the party.', 'https://api.dictionaryapi.dev/media/pronunciations/en/chocolate-us.mp3'),
('J1', 'vanilla milkshake', 'I ordered a sweet vanilla milkshake.', 'https://api.dictionaryapi.dev/media/pronunciations/en/vanilla-us.mp3'),
('J1', 'tuna sandwich', 'She packed a tuna sandwich for lunch.', 'https://api.dictionaryapi.dev/media/pronunciations/en/tuna-us.mp3'),
('J1', 'strawberry ice cream', 'I love strawberry ice cream on hot days.', 'https://api.dictionaryapi.dev/media/pronunciations/en/strawberry-us.mp3'),
('J1', 'cheap', 'This pen is very cheap.', 'https://api.dictionaryapi.dev/media/pronunciations/en/cheap-us.mp3'),
('J1', 'French fries', 'Crispy French fries are delicious.', 'https://api.dictionaryapi.dev/media/pronunciations/en/french-us.mp3'),
('J1', 'expensive', 'That diamond ring is expensive.', 'https://api.dictionaryapi.dev/media/pronunciations/en/expensive-us.mp3'),
('J1', 'cereal', 'I eat cereal with milk for breakfast.', 'https://api.dictionaryapi.dev/media/pronunciations/en/cereal-us.mp3'),
('J1', 'potato', 'Mashed potato goes well with meat.', 'https://api.dictionaryapi.dev/media/pronunciations/en/potato-us.mp3'),
('J1', 'favourite food', 'Pizza is my favourite food.', 'https://api.dictionaryapi.dev/media/pronunciations/en/favourite-us.mp3'),
('J1', 'some tomatoes', 'Add some fresh tomatoes to the salad.', 'https://api.dictionaryapi.dev/media/pronunciations/en/some-us.mp3'),
('J1', 'Do you like pasta?', 'Do you like pasta? Yes, I do!', 'https://api.dictionaryapi.dev/media/pronunciations/en/do-us.mp3'),
('J1', 'Anything else?', 'Would you like anything else? No, thank you.', 'https://api.dictionaryapi.dev/media/pronunciations/en/anything-us.mp3'),
('J1', 'No, thanks.', 'No, thanks. I am full.', 'https://api.dictionaryapi.dev/media/pronunciations/en/no-us.mp3'),
('J1', 'Here you are.', 'Here you are. Enjoy your food!', 'https://api.dictionaryapi.dev/media/pronunciations/en/here-us.mp3'),
('J1', 'Thank you.', 'Thank you for your help!', 'https://api.dictionaryapi.dev/media/pronunciations/en/thank-us.mp3'),
('J1', 'You''re welcome.', 'You''re welcome! Have a nice day.', 'https://api.dictionaryapi.dev/media/pronunciations/en/youre-us.mp3'),
('J1', 'How much is it?', 'How much is it? It costs five dollars.', 'https://api.dictionaryapi.dev/media/pronunciations/en/how-us.mp3'),
('J1', 'It''s cheap.', 'This toy is cheap.', 'https://api.dictionaryapi.dev/media/pronunciations/en/its-us.mp3'),
('J1', 'It''s expensive.', 'That bike is very expensive.', 'https://api.dictionaryapi.dev/media/pronunciations/en/its-us.mp3'),
('J1', 'green T-shirt', 'He is wearing a green T-shirt.', 'https://api.dictionaryapi.dev/media/pronunciations/en/green-us.mp3'),
('J1', 'purple crayon', 'Draw a flower with a purple crayon.', 'https://api.dictionaryapi.dev/media/pronunciations/en/purple-us.mp3'),
('J1', 'red bike', 'She rides her red bike to school.', 'https://api.dictionaryapi.dev/media/pronunciations/en/red-us.mp3'),
('J1', 'blue bag', 'Put your books in the blue bag.', 'https://api.dictionaryapi.dev/media/pronunciations/en/blue-us.mp3'),
('J1', 'grey chair', 'Sit down on the grey chair.', 'https://api.dictionaryapi.dev/media/pronunciations/en/grey-us.mp3'),
('J1', 'pink sofa', 'Our cat is sleeping on the pink sofa.', 'https://api.dictionaryapi.dev/media/pronunciations/en/pink-us.mp3');
