-- ============================================================
-- SCRIPT SQL: INSERÇÃO DAS PALAVRAS E FRASES DO ESTÁGIO J2
-- Tabela: public.palavras_spelling
-- Nível: J2 (113 itens únicos deduplicados)
-- Execute este script no SQL Editor do Supabase
-- ============================================================

-- Remover registros anteriores de nível J2 (opcional, para recarga limpa)
DELETE FROM public.palavras_spelling WHERE level = 'J2';

INSERT INTO public.palavras_spelling (level, word, sentence, audio_url) VALUES
('J2', 'purple blouse', 'She wore a purple blouse to the party.', 'https://api.dictionaryapi.dev/media/pronunciations/en/purple-us.mp3'),
('J2', 'brown boots', 'He wears brown boots in the rain.', 'https://api.dictionaryapi.dev/media/pronunciations/en/brown-us.mp3'),
('J2', 'white cap', 'Put on your white cap to block the sun.', 'https://api.dictionaryapi.dev/media/pronunciations/en/white-us.mp3'),
('J2', 'pink dress', 'The little girl picked a pink dress.', 'https://api.dictionaryapi.dev/media/pronunciations/en/pink-us.mp3'),
('J2', 'flip flops', 'Wear flip flops when going to the beach.', 'https://api.dictionaryapi.dev/media/pronunciations/en/flip-us.mp3'),
('J2', 'pyjamas', 'Put on your warm pyjamas before bedtime.', 'https://api.dictionaryapi.dev/media/pronunciations/en/pyjamas-us.mp3'),
('J2', 'polo shirt', 'He wore a smart blue polo shirt.', 'https://api.dictionaryapi.dev/media/pronunciations/en/polo-us.mp3'),
('J2', 'green scarf', 'She wrapped a green scarf around her neck.', 'https://api.dictionaryapi.dev/media/pronunciations/en/green-us.mp3'),
('J2', 'grey shorts', 'He wore grey shorts on the hot afternoon.', 'https://api.dictionaryapi.dev/media/pronunciations/en/grey-us.mp3'),
('J2', 'red skirt', 'She loves wearing her red skirt.', 'https://api.dictionaryapi.dev/media/pronunciations/en/red-us.mp3'),
('J2', 'yellow socks', 'The clown wore bright yellow socks.', 'https://api.dictionaryapi.dev/media/pronunciations/en/yellow-us.mp3'),
('J2', 'blue sweater', 'Keep warm with this blue sweater.', 'https://api.dictionaryapi.dev/media/pronunciations/en/blue-us.mp3'),
('J2', 'sweatshirt', 'He put on a comfortable hooded sweatshirt.', 'https://api.dictionaryapi.dev/media/pronunciations/en/sweatshirt-us.mp3'),
('J2', 'tablet', 'I use my tablet to read digital books.', 'https://api.dictionaryapi.dev/media/pronunciations/en/tablet-us.mp3'),
('J2', 'It''s his watch.', 'Look at that wristwatch; it''s his watch.', 'https://api.dictionaryapi.dev/media/pronunciations/en/its-us.mp3'),
('J2', 'They''re her jackets.', 'Those coats on the rack, they''re her jackets.', 'https://api.dictionaryapi.dev/media/pronunciations/en/theyre-us.mp3'),
('J2', 'orange hat', 'She wore a bright orange hat.', 'https://api.dictionaryapi.dev/media/pronunciations/en/orange-us.mp3'),
('J2', 'speakers', 'Connect the Bluetooth speakers to play music.', 'https://api.dictionaryapi.dev/media/pronunciations/en/speakers-us.mp3'),
('J2', 'earphones', 'Put in your earphones to listen quietly.', 'https://api.dictionaryapi.dev/media/pronunciations/en/earphones-us.mp3'),
('J2', 'laptop', 'She types her homework on her laptop.', 'https://api.dictionaryapi.dev/media/pronunciations/en/laptop-us.mp3'),
('J2', 'smartwatch', 'His smartwatch tracks his daily steps.', 'https://api.dictionaryapi.dev/media/pronunciations/en/smartwatch-us.mp3'),
('J2', 'scooter', 'He rode his electric scooter down the street.', 'https://api.dictionaryapi.dev/media/pronunciations/en/scooter-us.mp3'),
('J2', 'skateboard', 'She practiced tricks on her new skateboard.', 'https://api.dictionaryapi.dev/media/pronunciations/en/skateboard-us.mp3'),
('J2', 'tent', 'We pitched a yellow tent at the campsite.', 'https://api.dictionaryapi.dev/media/pronunciations/en/tent-us.mp3'),
('J2', 'bedroom', 'My bedroom has a cozy bed.', 'https://api.dictionaryapi.dev/media/pronunciations/en/bedroom-us.mp3'),
('J2', 'bathroom', 'The bathroom has clean white tiles.', 'https://api.dictionaryapi.dev/media/pronunciations/en/bathroom-us.mp3'),
('J2', 'sitting room', 'Our family gathers in the sitting room.', 'https://api.dictionaryapi.dev/media/pronunciations/en/sitting-us.mp3'),
('J2', 'dining room', 'We had Thanksgiving dinner in the dining room.', 'https://api.dictionaryapi.dev/media/pronunciations/en/dining-us.mp3'),
('J2', 'kitchen', 'Delicious smells came from the kitchen.', 'https://api.dictionaryapi.dev/media/pronunciations/en/kitchen-us.mp3'),
('J2', 'hall', 'Walk down the long hall to reach the room.', 'https://api.dictionaryapi.dev/media/pronunciations/en/hall-us.mp3'),
('J2', 'attic', 'Old boxes are stored up in the attic.', 'https://api.dictionaryapi.dev/media/pronunciations/en/attic-us.mp3'),
('J2', 'laundry', 'Put the dirty clothes in the laundry basket.', 'https://api.dictionaryapi.dev/media/pronunciations/en/laundry-us.mp3'),
('J2', 'garage', 'Dad parked the car in the garage.', 'https://api.dictionaryapi.dev/media/pronunciations/en/garage-us.mp3'),
('J2', 'stairs', 'Walk carefully down the wooden stairs.', 'https://api.dictionaryapi.dev/media/pronunciations/en/stairs-us.mp3'),
('J2', 'curtains', 'Close the curtains to block the light.', 'https://api.dictionaryapi.dev/media/pronunciations/en/curtains-us.mp3'),
('J2', 'cushion', 'Place a soft cushion on the sofa.', 'https://api.dictionaryapi.dev/media/pronunciations/en/cushion-us.mp3'),
('J2', 'fridge', 'Keep the fresh milk inside the fridge.', 'https://api.dictionaryapi.dev/media/pronunciations/en/fridge-us.mp3'),
('J2', 'microwave', 'Warm up your soup in the microwave.', 'https://api.dictionaryapi.dev/media/pronunciations/en/microwave-us.mp3'),
('J2', 'shelf', 'Put the books back on the top shelf.', 'https://api.dictionaryapi.dev/media/pronunciations/en/shelf-us.mp3'),
('J2', 'shower', 'Take a quick shower before breakfast.', 'https://api.dictionaryapi.dev/media/pronunciations/en/shower-us.mp3'),
('J2', 'stove', 'Mom boiled water on the gas stove.', 'https://api.dictionaryapi.dev/media/pronunciations/en/stove-us.mp3'),
('J2', 'toilet', 'Remember to flush the toilet.', 'https://api.dictionaryapi.dev/media/pronunciations/en/toilet-us.mp3'),
('J2', 'wardrobe', 'Hang your coats inside the wooden wardrobe.', 'https://api.dictionaryapi.dev/media/pronunciations/en/wardrobe-us.mp3'),
('J2', 'lamp', 'Turn on the desk lamp to read.', 'https://api.dictionaryapi.dev/media/pronunciations/en/lamp-us.mp3'),
('J2', 'There''s a fridge.', 'There''s a fridge in the kitchen.', ''),
('J2', 'There isn''t a ball.', 'Look in the yard; there isn''t a ball.', ''),
('J2', 'there aren''t', 'There aren''t any cookies left.', ''),
('J2', 'Yes, there are.', 'Are there chairs? Yes, there are.', ''),
('J2', 'some chairs', 'We need some chairs for the guests.', ''),
('J2', 'any beds', 'Are there any beds available in the hotel?', ''),
('J2', 'grandfather', 'My grandfather loves gardening.', 'https://api.dictionaryapi.dev/media/pronunciations/en/grandfather-us.mp3'),
('J2', 'grandmother', 'My grandmother makes tasty pies.', 'https://api.dictionaryapi.dev/media/pronunciations/en/grandmother-us.mp3'),
('J2', 'brother', 'My brother is older than me.', 'https://api.dictionaryapi.dev/media/pronunciations/en/brother-us.mp3'),
('J2', 'sister', 'My sister plays the piano.', 'https://api.dictionaryapi.dev/media/pronunciations/en/sister-us.mp3'),
('J2', 'parents', 'My parents support me in everything.', 'https://api.dictionaryapi.dev/media/pronunciations/en/parents-us.mp3'),
('J2', 'cousin', 'My cousin lives in another city.', 'https://api.dictionaryapi.dev/media/pronunciations/en/cousin-us.mp3'),
('J2', 'siblings', 'I have two siblings, a brother and a sister.', 'https://api.dictionaryapi.dev/media/pronunciations/en/siblings-us.mp3'),
('J2', 'daughter', 'Their daughter started elementary school.', 'https://api.dictionaryapi.dev/media/pronunciations/en/daughter-us.mp3'),
('J2', 'son', 'His son loves playing soccer.', 'https://api.dictionaryapi.dev/media/pronunciations/en/son-us.mp3'),
('J2', 'aunt', 'My aunt visited us during the holidays.', 'https://api.dictionaryapi.dev/media/pronunciations/en/aunt-us.mp3'),
('J2', 'uncle', 'My uncle takes us fishing.', 'https://api.dictionaryapi.dev/media/pronunciations/en/uncle-us.mp3'),
('J2', 'mum', 'My mum baked a cake.', 'https://api.dictionaryapi.dev/media/pronunciations/en/mum-us.mp3'),
('J2', 'dad', 'My dad fixed the broken bicycle.', 'https://api.dictionaryapi.dev/media/pronunciations/en/dad-us.mp3'),
('J2', 'thirteen', 'There are thirteen cupcakes in the box.', 'https://api.dictionaryapi.dev/media/pronunciations/en/thirteen-us.mp3'),
('J2', 'fourteen', 'He is fourteen years old.', 'https://api.dictionaryapi.dev/media/pronunciations/en/fourteen-us.mp3'),
('J2', 'twenty-two', 'There are twenty-two players on the pitch.', 'https://api.dictionaryapi.dev/media/pronunciations/en/twenty-two-us.mp3'),
('J2', 'thirty-three', 'The house number is thirty-three.', 'https://api.dictionaryapi.dev/media/pronunciations/en/thirtythree-us.mp3'),
('J2', 'forty-four', 'Look at page forty-four.', 'https://api.dictionaryapi.dev/media/pronunciations/en/fortyfour-us.mp3'),
('J2', 'fifty-five', 'My mother is fifty-five today.', 'https://api.dictionaryapi.dev/media/pronunciations/en/fiftyfive-us.mp3'),
('J2', 'sixty-six', 'The highway is route sixty-six.', 'https://api.dictionaryapi.dev/media/pronunciations/en/sixtysix-us.mp3'),
('J2', 'seventy-seven', 'He scored seventy-seven on his test.', 'https://api.dictionaryapi.dev/media/pronunciations/en/seventyseven-us.mp3'),
('J2', 'eighty-eight', 'There are eighty-eight keys on a grand piano.', 'https://api.dictionaryapi.dev/media/pronunciations/en/eightyeight-us.mp3'),
('J2', 'ninety-nine', 'The price is ninety-nine dollars.', 'https://api.dictionaryapi.dev/media/pronunciations/en/ninety-us.mp3'),
('J2', 'one hundred', 'I got one hundred percent on the quiz.', 'https://api.dictionaryapi.dev/media/pronunciations/en/one-us.mp3'),
('J2', 'one hundred and twelve', 'The building has one hundred and twelve windows.', 'https://api.dictionaryapi.dev/media/pronunciations/en/one-us.mp3'),
('J2', 'an English book', 'Open your English book and read.', 'https://api.dictionaryapi.dev/media/pronunciations/en/english-us.mp3'),
('J2', 'an alarm clock', 'Set an alarm clock for seven in the morning.', 'https://api.dictionaryapi.dev/media/pronunciations/en/alarm-us.mp3'),
('J2', 'whiteboard', 'The teacher wrote the lesson on the whiteboard.', 'https://api.dictionaryapi.dev/media/pronunciations/en/whiteboard-us.mp3'),
('J2', 'wallet', 'He keeps his pocket money in his leather wallet.', 'https://api.dictionaryapi.dev/media/pronunciations/en/wallet-us.mp3'),
('J2', 'pear', 'A sweet juicy pear is a great snack.', 'https://api.dictionaryapi.dev/media/pronunciations/en/pear-us.mp3'),
('J2', 'plum', 'A purple plum is sweet and delicious.', 'https://api.dictionaryapi.dev/media/pronunciations/en/plum-us.mp3'),
('J2', 'lychee', 'Lychee is a sweet tropical fruit.', 'https://api.dictionaryapi.dev/media/pronunciations/en/lychee-us.mp3'),
('J2', 'pineapple', 'Pineapple is yellow and sweet inside.', 'https://api.dictionaryapi.dev/media/pronunciations/en/pineapple-us.mp3'),
('J2', 'strawberry', 'She picked a ripe red strawberry.', 'https://api.dictionaryapi.dev/media/pronunciations/en/strawberry-us.mp3'),
('J2', 'watermelon', 'Watermelon is refreshing on hot summer days.', 'https://api.dictionaryapi.dev/media/pronunciations/en/watermelon-us.mp3'),
('J2', 'They''re cherries.', 'Look at the red fruit; they''re cherries.', 'https://api.dictionaryapi.dev/media/pronunciations/en/theyre-us.mp3'),
('J2', 'They''re peaches.', 'Those sweet fruits, they''re peaches.', 'https://api.dictionaryapi.dev/media/pronunciations/en/theyre-us.mp3'),
('J2', 'tomato soup', 'Hot tomato soup is great on cold days.', 'https://api.dictionaryapi.dev/media/pronunciations/en/tomato-us.mp3'),
('J2', 'fried chicken', 'We ordered crispy fried chicken for dinner.', 'https://api.dictionaryapi.dev/media/pronunciations/en/fried-us.mp3'),
('J2', 'baked potato', 'Top the baked potato with cheese.', 'https://api.dictionaryapi.dev/media/pronunciations/en/baked-us.mp3'),
('J2', 'chocolate muffin', 'She bought a delicious chocolate muffin.', 'https://api.dictionaryapi.dev/media/pronunciations/en/chocolate-us.mp3'),
('J2', 'sausages', 'We grilled breakfast sausages on the barbecue.', 'https://api.dictionaryapi.dev/media/pronunciations/en/sausages-us.mp3'),
('J2', 'mashed potatoes', 'Creamy mashed potatoes go well with gravy.', 'https://api.dictionaryapi.dev/media/pronunciations/en/mashed-us.mp3'),
('J2', 'roast beef', 'Sunday dinner included tender roast beef.', 'https://api.dictionaryapi.dev/media/pronunciations/en/roast-us.mp3'),
('J2', 'grilled cheese sandwich', 'I ate a warm grilled cheese sandwich.', 'https://api.dictionaryapi.dev/media/pronunciations/en/grilled-us.mp3'),
('J2', 'a glass of soda', 'He drank a glass of soda with his meal.', 'https://api.dictionaryapi.dev/media/pronunciations/en/glass-us.mp3'),
('J2', 'a bowl of fruit salad', 'Enjoy a refreshing bowl of fruit salad.', 'https://api.dictionaryapi.dev/media/pronunciations/en/bowl-us.mp3'),
('J2', 'a jug of juice', 'Mom poured a jug of juice for everyone.', 'https://api.dictionaryapi.dev/media/pronunciations/en/jug-us.mp3'),
('J2', 'spaghetti with meatballs', 'We cooked spaghetti with meatballs for dinner.', 'https://api.dictionaryapi.dev/media/pronunciations/en/spaghetti-us.mp3'),
('J2', 'lime cupcake', 'She decorated a green lime cupcake.', 'https://api.dictionaryapi.dev/media/pronunciations/en/lime-us.mp3'),
('J2', 'English book', 'Open your English book and read.', 'https://api.dictionaryapi.dev/media/pronunciations/en/english-us.mp3'),
('J2', 'alarm clock', 'Set an alarm clock for seven in the morning.', 'https://api.dictionaryapi.dev/media/pronunciations/en/alarm-us.mp3'),
('J2', 'cherries', 'We picked sweet red cherries from the tree.', 'https://api.dictionaryapi.dev/media/pronunciations/en/cherries-us.mp3'),
('J2', 'peaches', 'Fresh peaches are soft and sweet.', 'https://api.dictionaryapi.dev/media/pronunciations/en/peaches-us.mp3'),
('J2', 'glass', 'He filled a glass with water.', 'https://api.dictionaryapi.dev/media/pronunciations/en/glass-us.mp3'),
('J2', 'bowl', 'A bowl of warm cereal is great.', 'https://api.dictionaryapi.dev/media/pronunciations/en/bowl-us.mp3'),
('J2', 'fruit salad', 'Fresh fruit salad is healthy.', 'https://api.dictionaryapi.dev/media/pronunciations/en/fruit-us.mp3'),
('J2', 'jug', 'Fill the glass from the glass jug.', 'https://api.dictionaryapi.dev/media/pronunciations/en/jug-us.mp3'),
('J2', 'juice', 'I like orange juice with breakfast.', 'https://api.dictionaryapi.dev/media/pronunciations/en/juice-us.mp3'),
('J2', 'spaghetti', 'We ate spaghetti for lunch.', 'https://api.dictionaryapi.dev/media/pronunciations/en/spaghetti-us.mp3'),
('J2', 'meatballs', 'Add meatballs to the pasta sauce.', 'https://api.dictionaryapi.dev/media/pronunciations/en/meatballs-us.mp3'),
('J2', 'jackets', 'Hang your heavy winter jackets here.', 'https://api.dictionaryapi.dev/media/pronunciations/en/jackets-us.mp3');
